// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB96ZhDx4-g-wXbLHwaIeA9xn8NC11M3n0',
    appId: '1:398584714896:web:84759353c54abe8e1daa15',
    messagingSenderId: '398584714896',
    projectId: 'region21-d85e5',
    authDomain: 'region21-d85e5.firebaseapp.com',
    storageBucket: 'region21-d85e5.firebasestorage.app',
    measurementId: 'G-SZ8WGD9F43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRsHS6jiwWAFNZNviyAaUz5fsQQgNA5W8',
    appId: '1:398584714896:android:4cd91016349c02031daa15',
    messagingSenderId: '398584714896',
    projectId: 'region21-d85e5',
    storageBucket: 'region21-d85e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMYZB4tMsfWqGPw5CgWF9xRmukHfO9mds',
    appId: '1:398584714896:ios:0d8714edef6906801daa15',
    messagingSenderId: '398584714896',
    projectId: 'region21-d85e5',
    storageBucket: 'region21-d85e5.firebasestorage.app',
    iosBundleId: 'com.example.region21',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMYZB4tMsfWqGPw5CgWF9xRmukHfO9mds',
    appId: '1:398584714896:ios:0d8714edef6906801daa15',
    messagingSenderId: '398584714896',
    projectId: 'region21-d85e5',
    storageBucket: 'region21-d85e5.firebasestorage.app',
    iosBundleId: 'com.example.region21',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB96ZhDx4-g-wXbLHwaIeA9xn8NC11M3n0',
    appId: '1:398584714896:web:15fc715fe693eb661daa15',
    messagingSenderId: '398584714896',
    projectId: 'region21-d85e5',
    authDomain: 'region21-d85e5.firebaseapp.com',
    storageBucket: 'region21-d85e5.firebasestorage.app',
    measurementId: 'G-Q1714WS4CY',
  );

}